
import React from 'react';
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import jsPDF from 'jspdf';
import { useToast } from "@/hooks/use-toast";

interface KarmicReportPDFExportProps {
  language: 'hi' | 'en';
  reportData: any;
}

const KarmicReportPDFExport: React.FC<KarmicReportPDFExportProps> = ({ language, reportData }) => {
  const { toast } = useToast();

  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      
      // Set font
      doc.setFont('helvetica');
      
      // Colors
      const primaryColor = [90, 75, 218]; // #5A4BDA
      const textColor = [31, 41, 55]; // #1F2937
      
      let yPosition = 20;
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(90, 75, 218);
      doc.text('🪔 ' + (language === 'hi' ? 'आपकी व्यक्तिगत करियर कर्म रिपोर्ट' : 'Your Personalized Career Karma Report'), 20, yPosition);
      
      yPosition += 10;
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text(language === 'hi' ? 'आयु एस्ट्रो द्वारा उत्पन्न · ज्योतिष + NLP + जेमिनी AI द्वारा संचालित' : 'Generated by Ayu Astro · Powered by Jyotish + NLP + Gemini AI', 20, yPosition);
      
      yPosition += 15;
      doc.setDrawColor(90, 75, 218);
      doc.line(20, yPosition, 190, yPosition);
      yPosition += 15;
      
      // Section 1: Career Signature (Using actual data)
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '1. आपका कर्मिक करियर हस्ताक्षर' : '1. Your Karmic Career Signature', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      
      const signatureData = [
        [language === 'hi' ? 'लग्न' : 'Lagna', reportData?.lagna || 'Unknown'],
        [language === 'hi' ? 'चंद्र नक्षत्र' : 'Moon Nakshatra', reportData?.moonNakshatra || 'Unknown'],
        [language === 'hi' ? '10वां घर' : '10th House', reportData?.tenthHouseLord || 'Unknown'],
        [language === 'hi' ? 'वर्तमान दशा' : 'Current Dasha', reportData?.currentDasha || 'Unknown']
      ];
      
      signatureData.forEach(([key, value]) => {
        doc.text(`${key}: ${value}`, 25, yPosition);
        yPosition += 6;
      });
      
      yPosition += 10;
      
      // Section 2: Career Blocks (Using actual data)
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '2. करियर कर्म बाधाएं' : '2. Career Karma Blocks', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      
      if (reportData?.careerBlocks && reportData.careerBlocks.length > 0) {
        reportData.careerBlocks.forEach((block: string) => {
          const wrappedText = doc.splitTextToSize(`• ${block}`, 170);
          doc.text(wrappedText, 25, yPosition);
          yPosition += wrappedText.length * 6;
        });
      } else {
        doc.text('• ' + (language === 'hi' ? 'कोई प्रमुख बाधा नहीं मिली' : 'No major blocks detected'), 25, yPosition);
        yPosition += 6;
      }
      
      yPosition += 10;
      
      // Section 3: Ideal Career Roles (Using actual data)
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '3. आदर्श करियर पथ' : '3. Ideal Career Path', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      
      if (reportData?.idealCareers && reportData.idealCareers.length > 0) {
        reportData.idealCareers.forEach((career: any) => {
          doc.text(`• ${career.role}: ${career.reason}`, 25, yPosition);
          yPosition += 6;
        });
      }
      
      yPosition += 10;
      
      // Section 4: Timeline (Using actual data)
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '4. आपकी करियर समयरेखा' : '4. Your Career Timeline', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      if (reportData?.timeline) {
        const timelineText = doc.splitTextToSize(reportData.timeline, 170);
        doc.text(timelineText, 25, yPosition);
        yPosition += timelineText.length * 6 + 15;
      }
      
      // Section 5: Weekly Actions (Using actual data)
      if (yPosition > 230) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '5. साप्ताहिक कर्म कार्य' : '5. Weekly Karma Actions', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      
      if (reportData?.weeklyActions && reportData.weeklyActions.length > 0) {
        reportData.weeklyActions.forEach((action: any) => {
          const actionText = doc.splitTextToSize(`सप्ताह ${action.week}: ${action.action} (${action.planet})`, 170);
          doc.text(actionText, 25, yPosition);
          yPosition += actionText.length * 6;
        });
      }
      
      yPosition += 10;
      
      // Section 6: Remedies (Using actual data)
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '6. कर्मिक उपचार' : '6. Karmic Remedies', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(31, 41, 55);
      
      if (reportData?.remedies && reportData.remedies.length > 0) {
        reportData.remedies.forEach((remedy: string) => {
          const remedyText = doc.splitTextToSize(remedy, 170);
          doc.text(remedyText, 25, yPosition);
          yPosition += remedyText.length * 6;
        });
      }
      
      yPosition += 15;
      
      // Coach Message (Using actual data)
      if (yPosition > 220) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(16);
      doc.setTextColor(90, 75, 218);
      doc.text(language === 'hi' ? '7. आपके कर्मिक कोच का संदेश' : '7. Message from Your Karmic Coach', 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(12);
      doc.setTextColor(31, 41, 55);
      
      if (reportData?.coachMessage) {
        const splitMessage = doc.splitTextToSize(`"${reportData.coachMessage}"`, 150);
        doc.text(splitMessage, 25, yPosition);
        yPosition += splitMessage.length * 6 + 15;
      }
      
      // Footer
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(language === 'hi' ? 'आयु एस्ट्रो द्वारा उत्पन्न · स्विस एफेमेरिस + जेमिनी AI द्वारा संचालित' : 'Generated by Ayu Astro · Powered by Swiss Ephemeris + Gemini AI', 20, yPosition);
      yPosition += 6;
      doc.text(language === 'hi' ? 'आपका कर्मिक पथ पवित्र है। इसे मार्गदर्शन दें, प्रतिबंधित न करें।' : 'Your karmic path is sacred. Let it guide, not restrict you.', 20, yPosition);
      
      // Save the PDF
      const fileName = `personalized-karmic-career-report-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);
      
      toast({
        title: language === 'hi' ? "PDF डाउनलोड हो गया" : "PDF Downloaded",
        description: language === 'hi' ? "आपकी व्यक्तिगत कर्मिक रिपोर्ट सफलतापूर्वक डाउनलोड हो गई" : "Your personalized karmic report has been downloaded successfully"
      });
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: language === 'hi' ? "त्रुटि" : "Error",
        description: language === 'hi' ? "PDF बनाने में त्रुटि हुई" : "Error generating PDF",
        variant: "destructive"
      });
    }
  };

  return (
    <Button onClick={generatePDF} className="w-full sm:w-auto bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white">
      <Download className="w-4 h-4 mr-2" />
      {language === 'hi' ? '📥 PDF डाउनलोड करें' : '📥 Download PDF'}
    </Button>
  );
};

export default KarmicReportPDFExport;
