// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tplhoojwvynbpyhnarwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbGhvb2p3dnluYnB5aG5hcnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5Mzk1MTQsImV4cCI6MjA2MzUxNTUxNH0.kz4IzZsYxiwiQr-V_6_jrv-IGpVnfZyyXaCjrL1VB8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);